// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Identity.Client;
using System;
using System.Collections.Generic;

namespace MathMaster.Models;

public partial class FinishedTask
{
    public FinishedTask()
    {

    }

    public FinishedTask(int id, int uid, float percent) 
    {
        this.TaskID = id;
        this.UserID = uid;
        this.Percent = percent;
    }
    public int TaskID { get; set; }

    public int UserID { get; set; }

    public float Percent { get; set; }
}