// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MathMaster.Models;

public partial class Group
{
    public Group(int id, string name, int owner)
    {
        this.id = id;
        this.name = name;
        this.owner = owner;
    }

    public int id { get; set; }

    public string name { get; set; }

    public int owner { get; set; }
}