// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MathMaster.Models;

public partial class Institution
{
    public Institution() 
    {

    }

    public Institution(int id, string address, string country, string type, string phone, string mail, string plz)
    {
        this.id = id;
        this.address = address;
        this.country = country;
        this.type = type;
        this.phoneNumber = phone;
        this.mail = mail;
        this.postalCode = plz;
    }

    public int id { get; set; }

    public string address { get; set; }

    public string country { get; set; }

    public string type { get; set; }

    public string phoneNumber { get; set; }

    public string mail { get; set; }

    public string postalCode { get; set; }
}