// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace MathMaster.Models;

public partial class Task
{
    public Task(int nr, string name, string sector, int difficulty, int points, bool drawing, string quest, string answer, string source, int group, string image)
    {
        this.nr = nr;
        this.name = name;
        this.sector = sector;
        this.difficulty = difficulty;
        this.points = points;
        this.drawing = drawing;
        this.question = quest;
        this.answer = answer;
        this.source = source;
        this.group = group;
        this.imagePath = image;
    }

    public int nr { get; set; }

    public string name { get; set; }

    public string sector { get; set; }

    public int difficulty { get; set; }

    public int points { get; set; }

    public bool drawing { get; set; }

    public string question { get; set; }

    public string answer { get; set; }

    public string source { get; set; }

    public int group { get; set; }

    public string imagePath { get; set; }
}