// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MathMaster.Models;

public partial class Task
{
    public int nr { get; set; }

    public string name { get; set; }

    public string sector { get; set; }

    public int difficulty { get; set; }

    public int points { get; set; }

    public bool drawing { get; set; }

    public string question { get; set; }

    public string answer { get; set; }

    public string source { get; set; }

    public int group { get; set; }

    public string imagePath { get; set; }
}