// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MathMaster.Models;

public partial class Task
{
    public int ID { get; set; }

    public int Difficulty { get; set; }

    public int Defefe { get; set; }

    public int dfewfwerwerwrwe { get; set; }
}