// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MathMaster.Models;

public partial class User
{
    public int id { get; set; }

    public string username { get; set; }

    public string E_Mail { get; set; }

    public int points { get; set; }

    public string usertype { get; set; }

    public string lastLogin { get; set; }

    public string lastLogout { get; set; }

    public string birthDate { get; set; }

    public string password { get; set; }

    public int group { get; set; }
}