// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MathMaster.Models;

public partial class User
{
    public User()
    {

    }

    public User(int id, string username, string email, int points, string utype, string lastlogin, string lastLogout, string birthdate, string password, int group)
    {
        this.id = id;
        this.username = username;
        this.E_Mail = email;
        this.points = points;
        this.usertype = utype;
        this.lastLogin = lastlogin;
        this.lastLogout = lastLogout;
        this.birthDate = birthdate;
        this.password = password;
        this.group = group;
    }

    public int id { get; set; }

    public string username { get; set; }

    public string E_Mail { get; set; }

    public int points { get; set; }

    public string usertype { get; set; }

    public string lastLogin { get; set; }

    public string lastLogout { get; set; }

    public string birthDate { get; set; }

    public string password { get; set; }

    public int group { get; set; }
}