// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MathMaster.Models;

public partial class UserAndGroup
{
    public int UID { get; set; }

    public int GID { get; set; }
}